-- VoiceKhata minimal schema

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  shop_phone text not null,
  name text not null,
  name_norm text not null,
  created_at timestamptz not null default now(),
  unique (shop_phone, name_norm)
);

create table if not exists public.udhaar_entries (
  id bigint generated by default as identity primary key,
  shop_phone text not null,
  customer_id bigint not null references public.customers(id),
  amount numeric not null,
  transcript text,
  raw_text text,
  source_message_id text,
  reversed boolean not null default false,
  reversed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists udhaar_entries_shop_created_idx
  on public.udhaar_entries (shop_phone, created_at desc);

create index if not exists udhaar_entries_customer_idx
  on public.udhaar_entries (customer_id);

create table if not exists public.pending_actions (
  id bigint generated by default as identity primary key,
  shop_phone text not null,
  action_type text not null,
  action_json jsonb not null,
  status text not null default 'pending', -- pending | confirmed | cancelled | expired
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists pending_actions_shop_status_idx
  on public.pending_actions (shop_phone, status, created_at desc);

-- Payment holds / promises
-- WHY: Tracks "will pay later" items so a reminder agent can notify after N days.
create table if not exists public.payment_holds (
  id bigint generated by default as identity primary key,
  shop_phone text not null,
  customer_id bigint not null references public.customers(id),
  amount numeric not null,
  status text not null default 'open', -- open | resolved | cancelled
  hold_reason text,
  due_at timestamptz,
  created_at timestamptz not null default now(),
  last_notified_at timestamptz,
  notify_count int not null default 0,
  resolved_at timestamptz,
  resolved_note text
);

create index if not exists payment_holds_shop_status_created_idx
  on public.payment_holds (shop_phone, status, created_at desc);

create index if not exists payment_holds_shop_due_idx
  on public.payment_holds (shop_phone, due_at);

-- Notification audit log / outbox
create table if not exists public.notification_log (
  id bigint generated by default as identity primary key,
  shop_phone text not null,
  channel text not null, -- whatsapp | demo | other
  notification_type text not null, -- payment_hold_7d
  entity_table text not null,
  entity_id bigint not null,
  message text not null,
  status text not null default 'sent', -- pending | sent | failed
  provider_message_id text,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists notification_log_shop_created_idx
  on public.notification_log (shop_phone, created_at desc);

-- Grants for hackathon demo
-- WHY: If you use an anon/publishable key from the backend, PostgREST still needs explicit privileges.
-- For production, prefer RLS + policies and keep service role key server-only.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.customers to anon, authenticated;
grant select, insert, update, delete on table public.udhaar_entries to anon, authenticated;
grant select, insert, update, delete on table public.pending_actions to anon, authenticated;
grant select, insert, update, delete on table public.payment_holds to anon, authenticated;
grant select, insert, update, delete on table public.notification_log to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
